### ISSUE TITLE
How to use extraregressors

### ISSUE THREAD

**Issue by zieranna** [cvnlab/GLMsingle#101]
I have found this explanation on how to use extraregressors in my glm_single model.

<img width="825" alt="image" src="https://user-images.githubusercontent.com/2728338/153626402-074dc43a-82be-40d5-8e78-b9a7c9a7ad21.png">
I see.  OK, for path (3), I assume you will have to use the "extraregressors" feature, whereby you can include some predictors that will be fit to the data as part of the model.  Currently, it is set up such that these are specified per-run.  And you don't really get back the GLM weights that are associated with these terms.

_Originally posted by @kendrickkay in https://github.com/cvnlab/GLMsingle/discussions/26#discussioncomment-2158579_

However, I do not really understand how to specify the duration. 
In the original design matrix, I specify the time onset and afterwards the duration of this event.
Would I mark only the time onset in the additional design matrix or every time point said event is present?

**Comment by kendrickkay** [comment]
The <extraregressors> input is intended to be a fully specified predictor. (Like, an entire time series.) It's not intended to be in the style of the experimental conditions. Does that help? 

If your "extra" regressors are more like experimental events (or subevents), perhaps one strategy is to just specify them in the original design matrix and then ignore them (if you want).

**Comment by zieranna** [comment]
The problem with including the original experimental events, is, that they have different durations. 
My trial is built up in the following order: 1.5s encoding; 10.5s delay, 4.8s response. 
For the encoding and the response, the subject will receive visual input, whereas I am mainly interested in the effect of 4-10 s of the delay phase, Therefore, I specified the 4th second of the delay phase as input and the stimulus duration as 6 and included the 18 conditions of possible trial types as conditions in the design matrix. But as the delay phase might be influenced by the visual input of the encoding or the HRF might endure into the response , I would like to specify at some point that other events take place. 

How would you choose your settings for a design like this?

**Comment by kendrickkay** [comment]
I see.  The issue of different durations is discussed on the FAQ a bit.  

In short, it's a little tricky, but one idea is to imagine that your delay phase consists of a series of distinct "subtrials".  Then, you can just code all of the different phases of your trial (e.g. encoding, delay sub trials, response) as events.  In a sense, this is totally sensible --- the interpretation is that you are allowing your model to potentially estimate differing levels of activity during the delay period.  Of course, if you don't care about that, you can take the beta estimates that you get from GLMsingle and then just average them.

**Comment by kendrickkay** [comment]
(For example, you could just guessestimate the "event duration" to be 2 s, and then propose that you expect the signal from your experiment to consist of some brief neural event corresponding to the encoding, a series of neural events (sustained activity) during the delay period, and a neural event corresponding to the response.   In the end, the 2-s duration is really just used as a guess for the potential shapes of the HRFs (for each given voxel), so it's not that drastic of a choice.
