### ISSUE TITLE
changes to zerodiv.py causing errors

### ISSUE THREAD

**Issue by maggiemae13** [cvnlab/GLMsingle#103]
https://github.com/cvnlab/GLMsingle/blame/123741773e8035795f94a6bc818bf78f8b21edeb/glmsingle/utils/zerodiv.py#L54

Adding np.newaxis makes the results array the wrong shape. 

I.E. if x & y are matrices with shape (500,) the result should also be (500,) however with np.newaxis the result will be shape (500,500) 

This causes issues in two ways:

1. The matrix is gigantic and throws a Memory error when computing  f = x / tmp[:, np.newaxis], even with small chunk sizes.
2. If you just put in some small dummy data to get past the memory error, GLMSingle.py will crash when trying to run Model B as it uses the R2 from Model A, which is no longer the correct shape:

--> 773                     FitHRFR2[this_chunk, p] = results0['R2']
    774                     FitHRFR2run[this_chunk, :, p] = np.stack(
    775                         results0['R2run']).T

ValueError: shape mismatch: value array of shape (500,500) could not be broadcast to indexing result of shape (500,)

**Comment by iancharest** [comment]
this should be fixed with the latest zerodiv fix #107 .
