### ISSUE TITLE
Crash when running Colab demo from https://tinyurl.com/GLMsingle-demo

### ISSUE THREAD

**Issue by usernameandme** [cvnlab/GLMsingle#104]
This works well with release [1.1](https://github.com/cvnlab/GLMsingle/releases/tag/1.1). 
Getting the crash with the latest version of the code from the repo. 

```
results_glmsingle = glmsingle_obj.fit(
       design,
       data,
       stimdur,
       tr,
       outputdir='GLMsingle_outputs',
       figuredir='GLMsingle_figures')
```

*** FITTING TYPE-A MODEL (ONOFF) ***

fitting model...
done.

preparing output...
done.

computing model fits...
done.

computing R^2...
done.

computing SNR...
done.

*** Saving results to GLMsingle_outputs/TYPEA_ONOFF.npy. ***

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-8-be706dbccd60>](https://localhost:8080/#) in <cell line: 5>()
      3 
      4 # call GLMsingle (should take ~2 mins to run)
----> 5 results_glmsingle = glmsingle_obj.fit(
      6        design,
      7        data,

3 frames
[/usr/local/lib/python3.10/dist-packages/glmsingle/glmsingle.py](https://localhost:8080/#) in fit(self, design, data, stimdur, tr, outputdir, figuredir)
    632             if xyz:
    633                 results_out = {
--> 634                     'onoffR2': np.reshape(onoffR2, [nx, ny, nz]),
    635                     'meanvol': np.reshape(meanvol, [nx, ny, nz]),
    636                     'betasmd': np.reshape(betasmd, [nx, ny, nz])

/usr/local/lib/python3.10/dist-packages/numpy/core/overrides.py in reshape(*args, **kwargs)

[/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py](https://localhost:8080/#) in reshape(a, newshape, order)
    296            [5, 6]])
    297     """
--> 298     return _wrapfunc(a, 'reshape', newshape, order=order)
    299 
    300 

[/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py](https://localhost:8080/#) in _wrapfunc(obj, method, *args, **kwds)
     55 
     56     try:
---> 57         return bound(*args, **kwds)
     58     except TypeError:
     59         # A TypeError occurs if the object does have such a method in its

ValueError: cannot reshape array of size 160000 into shape (20,20,1)

**Comment by iancharest** [comment]
This is now fixed with the latest release of GLMsingle.
