### ISSUE TITLE
feature request: provide mask for top 1% voxels related to a runwiseFIR.png

### ISSUE THREAD

**Issue by andreifoldes** [cvnlab/GLMsingle#121]
Hello,

Much thanks for the cool diagnostics plot! 
I think it would help with following up on suspicious runs if users had access to the binary mask(s) of the voxels going into the runwiseFIR plot.

**Comment by andreifoldes** [comment]
Upon further reflection, these could be created by using thresholding the R2 map, although that's aggregated across runs.. still it would largely overlap right?

**Comment by kendrickkay** [comment]
<img width="696" alt="image" src="https://github.com/cvnlab/GLMsingle/assets/2728338/7afb74fe-e7d6-4d49-a3dc-ea02a5789598">
Yes, that is a good idea and is on my list of things to implement

**Comment by kendrickkay** [comment]
This has been implemented in the matlab version. (Python to soon follow).  See:

https://github.com/cvnlab/GLMsingle/commit/31f9eaa46e6f8c01cde49315826a0aef5cc674f1
