### ISSUE TITLE
AssertionError: <extra_regressors> should match the number of runs

### ISSUE THREAD

**Issue by banjogirl** [cvnlab/GLMsingle#125]
Hi - 

This seems like a great tool, thank you so much! 

I'm a total newbie, just trying to get example 1 to run. I'm getting this error (see below). Extra_regressors is set to False (per the example code, default). There are 12 runs in the sample data from what I see. 

It seems like this may be related to some new code you commited a week ago?

Sorry if this is an obvious question, I appreciate any help.

Thanks,
Maggie

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
[<ipython-input-16-68d4746d4a23>](https://swth7yfwp7j-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240123-060155_RC00_600685254#) in <cell line: 1>()
----> 1 results_glmsingle = glmsingle_obj.fit(
      2        design,
      3        data,
      4        stimdur,
      5        tr,

[/usr/local/lib/python3.10/dist-packages/glmsingle/glmsingle.py](https://swth7yfwp7j-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240123-060155_RC00_600685254#) in fit(self, design, data, stimdur, tr, outputdir, figuredir)
    490             err_msg='fracs must be less than or equal to 1')
    491 
--> 492         assert len(params['extra_regressors']) == numruns, '<extra_regressors> should match the number of runs'
    493 
    494         if figuredir is not None:

AssertionError: <extra_regressors> should match the number of runs

**Comment by jacob-prince** [comment]
I believe we have addressed this issue in the above pull request: https://github.com/cvnlab/GLMsingle/pull/126

please try again and reply here if there are any further issues. thanks!

**Comment by banjogirl** [comment]
It works! Thanks so much, I appreciate the timely response. 

I’m looking forward to digging in.

Maggie
