### ISSUE TITLE
Issue when running GLMsingle without cross-validation (no repeated trials)

### ISSUE THREAD

**Issue by biancasanti** [cvnlab/GLMsingle#138]
We are using GLMsingle to analyze data in which there are no repeated trials, and we wanted all four models with no cross-validation given that there are no repeats. The documentation specifies that you can run glmsingle with glmdenoise and fracridge without any repeated conditions as long as <pcstop> = -B and <fracs> is a single scalar value so that no cross-validation is run for denoising and fracridge.

However, when we ran GLMsingle (the python version) with <wantglmdenoise> = 1 and <wantfracridge> = 1, a negative <pcstop> value and a single scalar value for <fracs>, it only ran models A and B and didn't run models C and D. The main issue was that there is a block (lines 662-677 in glmsingle.py) that issues warnings if there are no repeats and then sets <wantglmdenoise> and <wantfracridge> to 0, with no exceptions if there's a negative <pcstop> value and a scalar <fracs> value. We fixed this for ourselves by manually removing the lines that set <wantglmdenoise> and <wantfracridge> to 0, which allowed the model to run correctly for our purposes (outputting all 4 model types with no cross-validation). 

While running glmsingle without repeats and without cross-validation is obviously not the main use case, it would be great if this could be fixed so that the script behaves as specified by the documentation when the correct values are given. Specifically, a fix that keeps the warning messages if there's no repeats but has an exception where <wantglmdenoise> and <wantfracridge> remain set to 1 if <pcstop> is negative and <fracs> is a scalar value should fix the issue.

**Comment by candemircan** [comment]
was just having the same issue :) would be great if you can fix this. thanks a lot!

**Comment by kendrickkay** [comment]
Fixed with #140
