### ISSUE TITLE
default GLMsingle calls generate small unlabeled fracvalue figure upon completion

### ISSUE THREAD

**Issue by jacob-prince** [cvnlab/GLMsingle#16]
![image](https://user-images.githubusercontent.com/35503086/129136965-404a7865-97cd-4aad-a921-5c916712be98.png)

- if such an output is desirable, we should make the fig slightly bigger and add labels, title, etc. 
- we might also consider plotting other outputs by default (R2?)
- if such an output is not desirable, we could just cut this bit of code...

**Comment by kendrickkay** [comment]
Hmm.  The MATLAB version just spits out a bunch of .png files (with no titles, etc.).  Perhaps the function itself could provide some textual description of what the figures mean (as opposed to having to spend time tweaking the figure code)?

**Comment by jacob-prince** [comment]
Agreed, adding description to the python function would be helpful. I should have specified that the above behavior only happens in the Python version. The behavior of the MATLAB version is great - all figures saved with descriptive titles to .png files and no random figures drawn and left open like in the above image ^. 

Looking at the python glmsingle figure outputs, there are a few other things that caught my attention that I think make it worthwhile to invest a few minutes in cleaning up.

I am planning to make the following super quick changes to the default Python GLMsingle behavior with respect to figures: 
- make sure the fracvalue fig closes properly after saving 
- make resolution/fig size larger so that the colorbar of all saved figs isn't weirdly large and the brains are more clearly visible across the board
- use a rainbow colormap for HRFindex to match matlab behavior, rather than viridis

**Comment by kendrickkay** [comment]
All sounds good

**Comment by iancharest** [comment]
fixed with #35
