### ISSUE TITLE
when HRF fitting is turned off, GLM beta outputs are vectorized even if user inputs volumetric data

### ISSUE THREAD

**Issue by jacob-prince** [cvnlab/GLMsingle#17]
- tiny thing, but we should be sure that "assume-HRF" outputs (e.g. when <wantlibrary> is false) have shape that matches the input data. 
- if user inputs vectorized/vertex data, output vectorized betas, meanvol, R2, etc. if user inputs volumetric data, output volumetric... etc.
- the current functionality causes minor headaches and creates the need to apply unexpected reshaping operations to GLMsingle outputs

![image](https://user-images.githubusercontent.com/35503086/129137096-aacd5833-4692-4e5a-b178-182e2ceaecd4.png)

**Comment by kendrickkay** [comment]
Hmm, i agree that inputs and outputs should match.  Sounds like Python-version bug/issue.   We can task Ian with this I suppose.

**Comment by jacob-prince** [comment]
should be a very easy fix. i could also do it myself if Ian is too busy

**Comment by iancharest** [comment]
Hi Guys,

feel free to make any changes you deem necessary.

ian

**Comment by kendrickkay** [comment]
@jacob-prince  - sorry, but I can't seem to reproduce your bug.   what I tried was to set "opt['wantlibrary'] = 0" and then run it.  after running, i checked results_glmsingle['typeb']['betasmd'].shape and it was X Y Z T as expected.  Can you provide some insight ?

**Comment by kendrickkay** [comment]
Either you fixed it, or Ian also recently fixed some output shapes.   So I think this bug is fixed.
