### ISSUE TITLE
if user turns off certain routines within GLMsingle (e.g. GLMdenoise), output beta filenames will be misleading

### ISSUE THREAD

**Issue by jacob-prince** [cvnlab/GLMsingle#22]
currently, in both matlab and python implementations, output filenames are hard-coded as follows:
- if TYPEC betas, assumption is that HRF fitting is turned on (e.g. TYPEC_FITHRF_GLMDENOISE.mat)
- if TYPED betas, assumption is that both HRF fitting and GLMdenoise are turned on 

thus, if users output TYPEC betas but turn off HRF fitting, or, output TYPED betas but turn off either HRF fitting or GLMdenoise, the output filenames will be misleading. 

a bug fix here would modify the output filenames appropriately to reflect the features that the user has turned on/off.
so if they ran only ridge regression with a canonical HRF and no denoising, the output would be "TYPED_RR" or even "TYPED_ASSUMEHRF_RR" if we wanted to be extra descriptive. similar functionality could even be added for the LSS cases...

it's possible that users should be left to "fend for themselves" here, but having files lying around that are mislabeled could create serious confusion if users don't create descriptive documentation for themselves to make sure they remember which output files correspond to a specific set of input parameters. 

here are the lines with the hard-coded output filenames:

![image](https://user-images.githubusercontent.com/35503086/144376586-b3fe3537-bd4f-4241-ba9b-4a5dbbe7a96f.png)

![image](https://user-images.githubusercontent.com/35503086/144376611-64c31e23-3fc0-4556-b520-a8cf1391b0cf.png)

**Comment by kendrickkay** [comment]
Hmm... Yeah, I agree this is a tricky issue.  I'm  not sure what's least bad?  Make generic filenames?  Make the user specify the filenames themselves?  Make extra-informative custom filenames?   These all have downsides....   ?

**Comment by kendrickkay** [comment]
Hmm, one idea is that we could make the filenames generic and then have the code save a little text file that documents exactly what was run/options/etc. to generate that version of the results.

**Comment by iancharest** [comment]
I think this is a case for users knowing what they do. Overall everything is carefully documented so should not be a major issue.

**Comment by kendrickkay** [comment]
Ian and I discussed and we feel it's okay to let users fend for themselves (i.e. keep track of what they are doing).

We feel the alternative (i.e. tailoring filenames) is even a worse solution.
