### ISSUE TITLE
Bug in check_inputs.py if runs have different number of TRs

### ISSUE THREAD

**Issue by gretatuckute** [cvnlab/GLMsingle#27]
Hi, thanks again for the great work on this! I encountered two bugs in the check_inputs.py script when I ran GLMsingle on runs with different TRs. 

Say I have 10 runs in total, where six of them have 148 TRs, and the remaining four have 152. My design variable will then be a list of length ten, each with 2D arrays of size [TR; num_cond]. During checking of the inputs, I had a bug [here](https://github.com/gretatuckute/GLMsingle/blob/main/glmsingle/check_inputs.py#L28) which I fixed by indexing into the design matrix by the run number of interest (p), instead of using np.unique on the list of design matrices. The second error is [here](https://github.com/gretatuckute/GLMsingle/blob/main/glmsingle/check_inputs.py#L65) when the data is being reshaped and the number of TRs used is from the first run (which will error for later runs with different number of TRs).

Otherwise, the pipeline should be able to handle runs with different number of TRs completely fine? Please let me know if not!

thanks a lot,
Greta

**Comment by kendrickkay** [comment]
Sorry for the delay.  should be fixed now!
