### ISSUE TITLE
Tasks are in a different order each time in each run of experiments

### ISSUE THREAD

**Issue by Cupid777** [cvnlab/GLMsingle#34]
Tasks are in a different order each time in each run of experiments.
How to deal with this problem?

**Comment by kendrickkay** [comment]
Can you clarify what you mean here? It is certainly not a problem that tasks (or experimental conditions) are presented in different/random orders in different runs. Perhaps you can check out the example scripts to see how those datasets are set up?

**Comment by kendrickkay** [comment]
As I haven't heard back yet, I am closing this.  But feel free to post a github discussion about your specific use case if you would like to discuss further.
