### ISSUE TITLE
np.save() not functional for outputs larger than 4GB

### ISSUE THREAD

**Issue by jacob-prince** [cvnlab/GLMsingle#4]
- glmsingle.py throws errors when users process large amounts of data and the resulting file outputs exceed a certain size (4GB). 
- we may want to add functionality that computes the size of outputs and saves as .npy if possible, else saves as hdf5. 
- another idea would be to automatically save outputs in single precision format if they are on the order of several GB...

**Comment by oliver-contier** [comment]
Just for the sake of completeness, here is the specific error message I get.

The results from the on/off model seem to be saved without problem (which makes sense). The error is thrown for the type B model. 

The error also occurs when I input data in single float precision (though not when I only select a single slice for debugging). Maybe the culprit is the sheer amount of trials and respective beta maps to be saved due to our faster experimental design.


```
100%|█████████████████████████████████████████████████████████████████████████| 60/60 [02:21<00:00,  2.36s/it]
*** FITTING TYPE-A MODEL (ONOFF) ***

fitting model...
done.

preparing output...
done.

computing model fits...
done.

computing R^2...
done.

computing SNR...
done.


*** Saving results to /LOCAL/ocontier/thingsmri/bids/code/sandbox/test_glmsingle/glmsingle/TYPEA_ONOFF.npy. ***

*** Setting brain R2 threshold to 0.0493711175666636 ***

*** FITTING TYPE-B MODEL (FITHRF) ***

chunks: 100%|██████████████████████████████████████████████████████████████| 1/1 [3:34:18<00:00, 12858.99s/it]

*** Saving results to /LOCAL/ocontier/thingsmri/bids/code/sandbox/test_glmsingle/glmsingle/TYPEB_FITHRF.npy. ***

Traceback (most recent call last):
  File "try_glmsingle.py", line 87, in <module>
    ))
  File "/LOCAL/ocontier/thingsmri/bids/code/external_libraries/GLMsingle/glmsingle/glmsingle.py", line 858, in fit
    np.save(
  File "<__array_function__ internals>", line 5, in save
  File "/home/ocontier/.conda/envs/glmsingle_testenv/lib/python3.8/site-packages/numpy/lib/npyio.py", line 529, in save
    format.write_array(fid, arr, allow_pickle=allow_pickle,
  File "/home/ocontier/.conda/envs/glmsingle_testenv/lib/python3.8/site-packages/numpy/lib/format.py", line 676, in write_array
    pickle.dump(array, fp, protocol=3, **pickle_kwargs)
OverflowError: serializing a bytes object larger than 4 GiB requires pickle protocol 4 or higher
```

**Comment by kendrickkay** [comment]
From the error message, it seems the easiest solution is just use "pickle protocol 4 or higher".  I'm fine if the user has to deal with that (as opposed to the code hand holding the user).

Regarding single precision, the MATLAB implementation already assumes/asks the user to supply the large fMRI data in single format.  ("We automatically convert <data> to single format if not already in single format.").   I don't know how the Python implementation handles this, but it seems fine if Python also assumes/converts single-format computations, also.

So, perhaps the action item is: use "protocol=4" in the pickle.dump call?   See https://stackoverflow.com/questions/23582489/python-pickle-protocol-choice

**Comment by kendrickkay** [comment]
I think the interim solution is @jacob-prince should complain to numpy people.   And warn GLMsingle users about 4GB limit and the workaround being to get the outputs in your workspace and save the outputs to HDF5 yourself.  I'll put the warning in the README. 

@iancharest do you have any ideas here?  Do you want to uniformly just change all files written by Python GLMsingle to HDF5   (or perhaps, just those that exceed 4GB)  ?
