### ISSUE TITLE
handling variabile stimulus duration 

### ISSUE THREAD

**Issue by eghbalhosseini** [cvnlab/GLMsingle#41]
Hi 

I am trying to implement GLMsingle on an experiment where trials have different TR length, and feeding stimdur as a vector instead of single variable, but the code errors out 
`glmsingle/hrf/gethrf.py", line 10, in getcanonicalhrf
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
`
wondering if the package supports variable trials with variable durations

**Comment by kendrickkay** [comment]
Currently, stimdur is required to be a scalar (i.e., one stimulus duration to be applied to all trials).  The issue of variable stimulus durations is a complex one.  It might be not a big deal if you specify the same duration for all trials.  You can check out the discussion here:  https://github.com/cvnlab/GLMsingle/discussions/26    

Can you describe your design a little, so we know what we are dealing with?

**Comment by eghbalhosseini** [comment]
Thank you for the detailed response. 
replies below: 
_What is your intention for the GLM analysis?_
here I want to extract the response to the stimuli. if I understand correctly what you mean be neural drive, then yes, the amplitude of response to a 4s stimuli would be different to a 1s stimuli. But for doing an RSA I take each stimuli as a different experiment condition. for now I am not taking the duration into account ( I guess I could add it as an additional parameter at some point). 

in any case, if we are only interested in extracting responses to individual stimuli, knowing that they are different conditions, and have different length, would I still be able to utilize the pipeline, albeit with some modifications?

**Comment by kendrickkay** [comment]
![image](https://user-images.githubusercontent.com/2728338/159572987-513127f0-afbb-44ec-bbdd-84a77fbd3224.png)

I see.  So my understanding is that for whatever reason, some of your experimental conditions have a longer duration than others.

Well, one approach is to simply ignore this.  Consider the attached figure.  This just shows a hypothetical HRF and what you might expect to happen for 1-s, 2-s, 3-s, 4-s long duration events.  Notice that the timecourses (on the left) have very different amplitudes.  And notice that the timecourses normalized to peak at 1 (on the right) certainly have different timecourse shapes, but the shapes are actually somewhat similar.

So, one approach is to just use a "average" stimulus duration of say, 2.5-s, and just try to let the GLM model get the "best fit" to your different stimulus conditions.  The idea is that the beta weights (representing response amplitude) will be what you are interested in, and the different "neural drive lengths" will show up in the beta weights (i.e., the longer stimulus durations are going to have higher amplitudes, and this will show up in the beta weights).

Does that make sense?

**Comment by eghbalhosseini** [comment]
So the reason for variable duration is using natural speech stimuli with variable length and content. 
if I where to assume 2.5 sec stimuli, then I am not sure how to align events in the experiment with the TR that are used in the glm estimation ( say : Trial1 : 2sec stim + 4 sec fixation , trial 2 : 4 sec stim + 4 sec fixation). 
is there a way to allow for flexible timing in glmsingle? I assume it would only affect the step of estimating the hrf family for each voxel

**Comment by kendrickkay** [comment]
I think my suggestion is:  code the onset of each of your two trials in the straightforward way (the onset of the 2-s stim, and the onset of the 4-s stim), and then use a "typical" stim duration in GLMsingle, like 2.5 s or something.  

Unless you are talking about issues regarding the sample rate of your data (your TR)?  If your TR doesn't align well with your trial onsets, you could simply temporally upsample your time-series data to a convenient desired rate.

**Comment by eghbalhosseini** [comment]
thanks, I will give it a try and see how it works. sorry for the confusion here. no the TRs align with trial onsets. so if I understand correctly in the new stim matrix the trials would be ) Trial1. (2.5 sec-stim + 3.5 sec-fixation) , Trial2. (2.5 sec-stim + 4.5 secs-fixation) ?

**Comment by kendrickkay** [comment]
Right, except I think you had a typo.  It would be:
1. 2.5s followed by 3.5s fixation
2. 2.5s followed by 5.5s fixation

Also, note that for GLMsingle, you only code the trial onsets, so the duration of the fixation gaps are implicit (and do not need specification).
