### ISSUE TITLE
FIR modeling

### ISSUE THREAD

**Issue by jacob-prince** [cvnlab/GLMsingle#47]
just a reminder that at some point we may want to add functionality that supports FIR modeling of voxel timecourses within the GLMsingle toolbox.

**Comment by kendrickkay** [comment]
Yep.  It turns out it's actually already in there.  Just needs example scripts to explain how it all works.

**Comment by kendrickkay** [comment]
This is covered in https://github.com/cvnlab/GLMsingle/issues/60
