### ISSUE TITLE
need to regenerate python example scripts since fig output bug was fixed

### ISSUE THREAD

**Issue by jacob-prince** [cvnlab/GLMsingle#48]
tiny agenda item - the python example scripts have an extra unlabeled figure output that arose from a bug, which we fixed in https://github.com/cvnlab/GLMsingle/commit/a29b6c9fde6f62a8e4786c763c64197d3b6d43c7. this is a reminder for me to rerun these scripts and regenerate the HTML files to remove this messy output.

**Comment by jacob-prince** [comment]
@kendrickkay @iancharest, @jk619... we can close this issue once I finish dealing with https://github.com/cvnlab/GLMsingle/issues/66 and also finish editing the latest example scripts.

**Comment by iancharest** [comment]
This is now fixed with the latest release.
