### ISSUE TITLE
(python) make fracridge/GLMsingle compatible with sklearn 1.0.x

### ISSUE THREAD

**Issue by jacob-prince** [cvnlab/GLMsingle#49]
fracridge requires sklearn 0.23.2, but moving forward it will become increasingly common for users to have have sklearn 1.0.x installed, which would present a dependency conflict and may cause analysis issues. 

for example, only in sklearn 1.0 was non-negative ridge regression introduced. if i wanted to use GLMsingle to process fMRI data and non-negative ridge regression to build an encoding model, i would currently not be able to do so in the same environment. 

whether or not this is currently an edge case, it would probably be useful to make fracridge/GLMsingle compatible with sklearn 1.0.x at some point. i imagine this would involve contacting Ariel Rokem.

**Comment by arokem** [comment]
Hey folks: I think that it would be great to make fracridge (and as a consequence, glmsingle) compatible with sklearn 1.0. However, there is one test that is currently failing with the newest version of sklearn: https://github.com/nrdg/fracridge/runs/6081850881?check_suite_focus=true#step:6:82, and that's been blocking this. I believe that it has to do with situations in which samples are weighted, a use-case that is apparently not properly implemented in the object-oriented interface of fracridge. I would love to fix that, but have not made progress beyond some cursory digging around the sklearn codebase to understand this issue better (and still do not).

**Comment by jacob-prince** [comment]
thanks for your effort to work this out. keep us posted

**Comment by kendrickkay** [comment]
@arokem - happy to zoom/discuss/chat about these and other (python) issues.  of course, i can't quite do python coding, but maybe I coudl be useful to think about the conceptual/stats stuff.

**Comment by arokem** [comment]
Hello again. I finally managed to do a focused sprint on this and update fracridge to support the newest version of sklearn (1.1 on Python 3.8 and up. I think it's ). See https://github.com/nrdg/fracridge/pull/31 for details. This PR introduces a change to the API of the FracRidgeRegressorCV object, but I suspect that you don't care about that. If anyone wants to take a look, I'd be happy for a review. If not, I will merge this in the next few days, and then cut a new release. I'll update here, so you can close this when that's all done.

**Comment by arokem** [comment]
I've release fracridge 2.0, which should resolve this issue. I just confirmed that when I install glmsingle from source I get fracridge 2.0 and scikit learn 1.1.1 (and also sklearn 0.0 😄, see #65). I believe this can be closed.

**Comment by kendrickkay** [comment]
Thanks for your solution!
