### ISSUE TITLE
documentation of <sessionindicator> argument

### ISSUE THREAD

**Issue by jacob-prince** [cvnlab/GLMsingle#5]
- in the python docstring and matlab function description, we may want to add detail - e.g. explicitly encourage users to input a <sessionindicator> if they are processing multiple sessions of data at once, and they suspect that there are non-trivial differences in units between sessions. 
- as written currently, the contexts in which this variable should be inputted are not obvious

**Comment by kendrickkay** [comment]
OK, i've updated the documentation in matlab world (see below).

%   <sessionindicator> (optional) is 1 x n (where n is the number of runs) with
%     positive integers indicating the run groupings that are interpreted as
%     "sessions". The purpose of this input is to allow for session-wise z-scoring
%     of single-trial beta weights for the purposes of hyperparameter evaluation. 
%     For example, if you are analyzing data aggregated from multiple scan sessions,
%     you may want beta weights to be z-scored per voxel within each session in order
%     to compensate for any potential gross changes in betas across scan sessions.
%     Note that the z-scoring has effect only INTERNALLY: it is used merely to 
%     calculate the cross-validation performance and the associated hyperparameter
%     selection; the outputs of this function do not reflect z-scoring, and the user
%     may wish to post-hoc apply z-scoring. Default: 1*ones(1,n) which means to interpret
%     all runs as coming from the same session.

@jacob-prince , i guess propagate this to python?
