### ISSUE TITLE
Handling condition onsets that are not aligned with TRs

### ISSUE THREAD

**Issue by efirdc** [cvnlab/GLMsingle#50]
Hi

I am trying to use GLMsingle for an experiment where condition onsets can occur at an arbitrary time within a 1.97s TR. I am not sure if this is a typical situation or one that GLMsingle can handle. If I recall NSD has a 1.6s TR, with new image onsets every 4s. Does this mean image and TR onsets were misaligned for NSD as well?

There is a function to make a design matrix in [nilearn](https://nilearn.github.io/modules/generated/nilearn.glm.first_level.make_first_level_design_matrix.html) that takes a DataFrame of events with the exact onsets. If I understand correctly, this implementation with offset the sampling of the HRF to account for the misalignment of TRs and condition onsets. Is there a way to emulate this behavior in GLMsingle? One possibility may be to resample the design matrix and fMRI time series to a higher temporal resolution, but this wouldn't be very efficient.

Any guidance would be appreciated.

Cory

**Comment by kendrickkay** [comment]
In NSD, the time-series data were pre-processed such that the time resolution was 1 s (in the high-res preparation) or 1.333 s (in the standard-res preparation).  Hence, after that, the design matrix can be easily specified to correspond to the 4-s trial rate.

GLMsingle can only accept design matrices and data that are "aligned" at some temporal sampling rate.

As you mention, one approach is to do some resampling (like we did in NSD). Could that be a workable path for your data situation?  It does, incur, some computational cost (RAM/CPU), but should be a reasonably effective approach, i think.  You may have to "round" your design matrix to the nearest time point, but this might be a small-ish effect.

**Comment by kendrickkay** [comment]
Also, perhaps some example scripts may be helpful, as mentioned in https://github.com/cvnlab/GLMsingle/issues/60
