### ISSUE TITLE
How to handle no crossing of 0.5 detected error?

### ISSUE THREAD

**Issue by cnwangy** [cvnlab/GLMsingle#51]
running parameters:
{'wantlibrary': 1, 'wantglmdenoise': 1, 'wantfracridge': 1, 'wantfileoutputs': [1, 1, 1, 1], 'wantmemoryoutputs': [0, 0, 0, 0], 'wantpercentbold': 1, 'numforhrf': 50, 'hrfthresh': 0.5, 'hrffitmask': 1, 'R2thresh': 0, 'hrfmodel': 'optimise', 'n_jobs': 1, 'n_pcs': 10, 'n_boots': 100, 'extra_regressors': False, 'chunklen': 45000, 'wantparametric': 0, 'wantlss': 0, 'brainthresh': [99.0, 0.1], 'brainR2': [], 'brainexclude': False, 'pcR2cutoff': [], 'pcR2cutoffmask': 1, 'pcstop': 1.05, 'fracs': array([1.  , 0.95, 0.9 , 0.85, 0.8 , 0.75, 0.7 , 0.65, 0.6 , 0.55, 0.5 ,
       0.45, 0.4 , 0.35, 0.3 , 0.25, 0.2 , 0.15, 0.1 , 0.05]), 'wantautoscale': 1, 'seed': 1650772067.7549427, 'suppressoutput': 0, 'lambda': 0}

error message:
Traceback (most recent call last):
  File "xxx/python3.6/site-packages/glmsingle/glmsingle.py", line 624, in fit
    thresh = findtailthreshold(onoffR2.flatten())[0]
  File "xxx/python3.6/site-packages/glmsingle/gmm/findtailthreshold.py", line 69, in findtailthreshold
    err_msg='no crossing of 0.5 detected')
  File "xxx/python3.6/site-packages/numpy/testing/_private/utils.py", line 421, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal: no crossing of 0.5 detected
 ACTUAL: False
 DESIRED: True

**Comment by kendrickkay** [comment]
Hi - I think this may be occurring from a specific dataset that doesn't seem to have much signal in it.  Can you provide some information, like what the onoffR2 values are like?  Or maybe even the data themselves or something?  That could inform what the fix to this could be.  One strategy is that the findtailthreshold function could just resort to some percentile of the distribution, but this is premature until we can really understand what is causing this.

**Comment by kendrickkay** [comment]
Actually, your observation may be related to this issue: https://github.com/cvnlab/GLMsingle/issues/54

The MATLAB change has been made, and we will do the Python change soon.  So that may reoslve your issue.

However, it may still require some scrutiny --- i would recommend inspecting the onoff R2 histogram to see what's going on. It could be that your data may have strangely low SNR which may be a sign of some other issue (e.g. design matrix miscoding, or something)

**Comment by cnwangy** [comment]
Thanks! It seemed to be solved by applying [https://github.com/cvnlab/GLMsingle/pull/55](url). However, the histogram of onoffR2 does look different from normal ones.
Histogram of data with this problem
![run1](https://user-images.githubusercontent.com/13940405/166185753-725cf6cc-476b-4bbe-a065-527d8860566d.png)
normal data
![run2](https://user-images.githubusercontent.com/13940405/166186979-d3b8e0ab-36c7-4bca-96e9-41ec6a05582f.png)

**Comment by kendrickkay** [comment]
The first histogram actually looks good in the sense that there appears to be lots of signal. Do the rest of the plots and outcome look reasonable?

**Comment by cnwangy** [comment]
Only the first histogram has this error. The other runs without error are more like the second histogram.

**Comment by kendrickkay** [comment]
I think I understand.   Just to be clear, the first histogram was resulting in the error prior to the pull request #55?  After the pull request, everything seems to be resolved?  Below is something I cooked up that is qualitatively similar to your plot. The new code should be producing results similar to that.  I will close this issue, but re-open if there are problems.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/2728338/166927742-9354bd0b-f11e-41b6-a81e-2f3409e8aa35.png">
