### ISSUE TITLE
[wishlist] flag allowing users to output condition-wise beta estimates rather than single-trial estimates?

### ISSUE THREAD

**Issue by jacob-prince** [cvnlab/GLMsingle#53]
if this wouldn't be a huge pain, might be nice to include. to boost GLMsingle as a wholesale replacement for other GLM software.

**Comment by kendrickkay** [comment]
Can you clarify what you mean by this?  Do you mean, have GLMsingle run, get single trial betas, and then have the code do the post-hoc averaging to provide the condition means (and maybe standard errors)?  So, like, do extra work for the user?

**Comment by jacob-prince** [comment]
I was thinking of a case where at all stages of processing the user wants to estimate a single beta value for each condition in the experiment, regardless of how many repeats there are. So a different approach than single-trial entirely.

**Comment by kendrickkay** [comment]
My read of this issue is that perhaps the action item is to do this: https://github.com/cvnlab/GLMsingle/issues/59
