### ISSUE TITLE
Save options to the file outputs?

### ISSUE THREAD

**Issue by kendrickkay** [cvnlab/GLMsingle#57]
Perhaps it might be useful to save the options used in a call to GLMestimatesingletrial to the file outputs?

**Comment by halphenfang** [comment]
Yes, please. Save option is in urgent need. I am new to this toolbox, and I wranggled around this toolbox for the past week and still don't know how to export the data into nii format just like spm would do. Or, could you please tell me how to save each of the single trial beta file that GLMsingle produced into nii? So that I can use other tool to read it and do further process.

**Comment by halphenfang** [comment]
For decoding analysis, the t map or z map is often prefered rather than beta map. It would be great if GLMsingle can have a function directely transforming the beta map to z map.

**Comment by kendrickkay** [comment]
> Yes, please. Save option is in urgent need. I am new to this toolbox, and I wranggled around this toolbox for the past week and still don't know how to export the data into nii format just like spm would do. Or, could you please tell me how to save each of the single trial beta file that GLMsingle produced into nii? So that I can use other tool to read it and do further process.

In theory, you should be able to just do a for-loop over the trial estimates and use a generic NIFTI saving tool to save each trial estimate out.




> For decoding analysis, the t map or z map is often prefered rather than beta map. It would be great if GLMsingle can have a function directely transforming the beta map to z map.

The scope of GLMsingle is to simply provide the user with good single trial estimates.  There are many downstream analyses that one can consider (like computing specific condition contrasts)... these seem out of scope of GLMsingle.

**Comment by abdulawi** [comment]
> Perhaps it might be useful to save the options used in a call to GLMestimatesingletrial to the file outputs?

Yes, please. I hope you can make additional options for saving the trials beta values as nii or img files. Hence, it becomes easier to export the estimated trails for further analysis using other toolboxes. Besides, I hope you can explain how to prepare the input data mat files, or a script that helps for that would be great.

**Comment by iancharest** [comment]
We have an example dedicated to saving results of GLMsingle as nifti. You can check it out [here](https://github.com/cvnlab/GLMsingle/blob/main/examples/example8_nifti_save.ipynb) and get inspiration for coding it on your outputs.
