### ISSUE TITLE
Give user some helpful reports on their design matrix?

### ISSUE THREAD

**Issue by kendrickkay** [cvnlab/GLMsingle#58]
Design matrices can be complex. It would be helpful to the user if the code provided some information on what is found in the design matrices. Things like:
- How many unique conditions? And they show up in how many runs?
- How many repeats per condtion?
- How many cases of cross-validation trials are there?

This might help the user flag issues with their supplied design matrices... and/or troubleshoot problems...

**Comment by kendrickkay** [comment]
Also, we should detect the common problem of the user specifying a trial that occurs at the very end of a run (and for which it is basically impossible to estimate a HRF amplitude for

**Comment by kendrickkay** [comment]
One idea is to: "spit out a warning, and then delete the trials from the ‘design’ variable that happen with XX s from the end of the run."

**Comment by iancharest** [comment]
This is now included in the latest release I believe. closing. feel free to reopen.
