### ISSUE TITLE
glmsingle.py docstring cleanup

### ISSUE THREAD

**Issue by jacob-prince** [cvnlab/GLMsingle#6]
- the docstring describes an input called <chunknum>, but this has been changed to <chunklen> in the code. we should either make naming consistent between matlab and python implementations (regardless of what's happening under the hood), or, keep existing names but add detail to docstring to avoid confusion
- docstring has leftover matlab terminology (e.g. <xvalscheme> is a “cell vector of vectors”)… needs cleanup, and clarity re: acceptable inputs, as users currently get errors for inputting a numpy array rather than a list.

**Comment by kendrickkay** [comment]
@iancharest - when you have a chance can you carefully go through / check the docstring of the python version?
