### ISSUE TITLE
IndexError after warning: too big, so taking a subset

### ISSUE THREAD

**Issue by ramroomh** [cvnlab/GLMsingle#63]
Hi there,

Following example 1 for python, I inputted 4 runs of fMRI event data preprocssed in fMRIprep (each run appended to a list in npy format). This data is in MNI152NLin2009cAsym 2mm isotropic space (XYZ x Time: 97 x 115 x 97 x 483). 

Got the following error:
`warning: too big, so taking a subset
Traceback (most recent call last):
  File "./glmsingle_bids_datasets.py", line 172, in <module>
    main()
  File "./glmsingle_bids_datasets.py", line 169, in main
    run_1st_level(processed, stimdur, tr_new)
  File "./glmsingle_bids_datasets.py", line 149, in run_1st_level
    outputdir=outdir)
  File "/group/tuominen/anaconda3/lib/python3.7/site-packages/glmsingle/glmsingle.py", line 695, in fit
    thresh = findtailthreshold(onoffR2.flatten())[0]
  File "/group/tuominen/anaconda3/lib/python3.7/site-packages/glmsingle/gmm/findtailthreshold.py", line 52, in findtailthreshold
    v2 = picksubset(v2, maxsz)
  File "/group/tuominen/anaconda3/lib/python3.7/site-packages/glmsingle/utils/picksubset.py", line 40, in picksubset
    fnot = m.flatten()[notf]
IndexError: arrays used as indices must be of integer (or boolean) type`

Here is the model I used:
`results = gs.fit(
    design,
    data,
    stimdur,
    tr,
    outputdir=outdir)`
Where design is a list of 4 design matrices (3 col each) in npy format, data is a list of 4 images in npy format, stimdur =4,  tr=1.

EDIT: This error does not occur in 3mm isotropic space, so seems there is an issue with handling larger image data.

I've also attached a screenshot of the error. Let me know if I can provide any other information.
<img width="946" alt="screenshot_error" src="https://user-images.githubusercontent.com/39342954/168313114-86ce1535-2b4f-4f91-ad27-2181d3b4eff7.png">

**Comment by Aya-Khalaf** [comment]
Hi,
I'm getting the exact same issue when using example_singletrial.py (https://github.com/cvnlab/GLMsingle/blob/main/example_singletrial.py ) to get single trial estimates. I have 8 runs of fMRI data preprocessed with fMRIprep. Number of volumes per run is variable ( ranging from 290 to 310 volumes) , TR =1.5, and stimdur =1. 

<img width="1192" alt="Screen Shot 2022-06-01 at 2 27 31 PM" src="https://user-images.githubusercontent.com/63745522/171476601-faa991f6-51a8-4c01-8a50-59c09c95f52c.png">

**Comment by jacob-prince** [comment]
this has been addressed by @LukasNeugebauer via #68 and #69. closing this issue.
