### ISSUE TITLE
ValueError when fitting GLMsingle with 'extra_regressors' added

### ISSUE THREAD

**Issue by HugoSix** [cvnlab/GLMsingle#67]
Hello !

When I try to fit a GLMsingle object with some 'extra_regressors', I get the following error : 

```
ValueError : The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
glmsingle.py line 1075, in fit
if not params['extra_regressors'] or \
```
I followed the docstring instruction to feed correct values : 
`<extra_regressors> (optional) is time x regressors or a list of elements that are each time x regressors. The dimensions of <extra_regressors> should mirror that of <design> (i.e. same number of runs, same number of time points)`

My code : 
```
opt = {'wantfileoutputs': [0, 0, 0, 0], 'chunklen' : 300000, 'extra_regressors' : noises}
glmsingle_obj = GLM_single(opt)
results = glmsingle_obj.fit(design = designs, data = data, stimdur = 2, tr = 2)
```
With : 
- designs : list of  N design matrices of shape (150,3) (150TR, 3 conditions)
- noises : list of N noise regressors matrices with shape (150, 9)
- data : list of N fMRI runs with shape (X, Y, Z, 150)

Other parameters of my GLMsingle: 
`{'chunklen': 300000, 'wantfileoutputs': [0, 0, 0, 0], 'numforhrf': 50, 'hrfthresh': 0.5, 'hrffitmask': 1, 'R2thresh': 0, 'hrfmodel': 'optimise', 'n_jobs': 1, 'n_pcs': 10, 'n_boots': 100, 'wantlibrary': 1, 'wantglmdenoise': 1, 'wantfracridge': 1, 'wantmemoryoutputs': [1, 1, 1, 1], 'wanthdf5': 0, 'wantparametric': 0, 'wantpercentbold': 1, 'wantlss': 0, 'brainthresh': [99.0, 0.1], 'brainR2': [], 'brainexclude': False, 'pcR2cutoff': [], 'pcR2cutoffmask': 1, 'pcstop': 1.05, 'fracs': array([1.  , 0.95, 0.9 , 0.85, 0.8 , 0.75, 0.7 , 0.65, 0.6 , 0.55, 0.5 , 0.45, 0.4 , 0.35, 0.3 , 0.25, 0.2 , 0.15, 0.1 , 0.05]), 'wantautoscale': 1, 'seed': 1654068656.129018, 'suppressoutput': 0, 'lambda': 0}`

To note : the process works fine with 'extra_regressors' = False

To me, it seems that I'm feeding the right data type and shape into the 'extra_regressors' option but I can't understand why I have this error.
Thank in advance for any help you can provide me with.

**Comment by kendrickkay** [comment]
Fixed with https://github.com/cvnlab/GLMsingle/pull/74
