### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'reshape'

### ISSUE THREAD

**Issue by LukasNeugebauer** [cvnlab/GLMsingle#68]
Hey there,

I just tried your toolbox for the first time. Since my data is too large, the toolbox is taking a subset. I also encountered the issue as in #63. After fixing this (I might create a pull request for that), the next error arises. I'll add a screenshot below:
![image](https://user-images.githubusercontent.com/33320293/171659779-e2acd134-1417-496b-a602-e06715f3c2c6.png)

I'm pretty sure it comes from line 52 in `findtailthreshold.py`. You probably only want the first output of `picksubset`, which I could include in the aforementioned PR, if that solves the issue and PRs from outsiders are welcome.

**Comment by kendrickkay** [comment]
Yes, if you think you have the fix, you are welcome to submit a PR. Thanks!

**Comment by jacob-prince** [comment]
this has been addressed by #69. thanks for the help @LukasNeugebauer.
