### ISSUE TITLE
ValueError in fracridge.py

### ISSUE THREAD

**Issue by Aya-Khalaf** [cvnlab/GLMsingle#70]
Hi,

I'm getting the error below in fracrdige.py while running type-c model. I have 8 runs of fMRI data preprocessed with fMRIprep. Number of volumes per run is variable ( ranging from 290 to 310 volumes) , TR =1.5, voxel size = 2x2x2 mm, and stimdur =1. Volume dim is 97x114x97 (MNI152NLin2009cAsym). It is worth to mention that I'm using the newest version created after fixing the issue described here https://github.com/cvnlab/GLMsingle/issues/63.

<img width="1192" alt="Screen Shot 2022-06-07 at 2 09 35 PM" src="https://user-images.githubusercontent.com/63745522/172452884-218e4c34-f6d3-4552-8538-c9d35596c1c8.png">

**Comment by kendrickkay** [comment]
Can you provide a sense of how you are calling GLMsingle? E.g. input parameters, size of your design and data matrices, etc.?

**Comment by kendrickkay** [comment]
Also, can you confirm that your installation of fracridge is up to date?
