### ISSUE TITLE
How to enable one model only instead of getting trial estimates for the four models?

### ISSUE THREAD

**Issue by Aya-Khalaf** [cvnlab/GLMsingle#71]
Hi,

Given the computational complexity of the algorithm, I tried to see if I can enable model D only since it combines all functionalities GLMsingle is introducing, but it seems there is no way to do that (please see below). 
<img width="585" alt="image" src="https://user-images.githubusercontent.com/63745522/172466999-d9767417-c72e-4286-a276-524a89ede46d.png">

**Comment by kendrickkay** [comment]
In terms of computational time, the algorithm must proceed through A,B,C in order to get to D.   In terms of memory, you can save memory by setting <wantmemoryoutputs> accordingly.  Finally, in terms of disk space, you can save only the outputs that you want/need via setting <wantfileoutputs>.
