### ISSUE TITLE
Poor results on "Deep image reconstruction" dataset.

### ISSUE THREAD

**Issue by efirdc** [cvnlab/GLMsingle#72]
Hi,

I am attempting to run GLMsingle on the dataset from [Shen et. al](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1006633). This was a visual fMRI experiment where images were displayed back to back for 8s each. They did not use a GLM in their preprocessing pipeline. Instead, they normalized each voxel by subtracting a linear trend line and dividing by the std. deviation. Then they took the mean of the time series values at 4, 6, 8, and 10 seconds after stimulus onset to account for the hemodynamic delay. 

We started with the [raw data](https://openneuro.org/datasets/ds001506/versions/1.3.1) that they released and preprocessed it using fmriprep v20.2.4. Unfortunately, the results of applying GLMsingle to this data are not looking great:

![image](https://user-images.githubusercontent.com/5416313/173336400-5c7728cc-8efd-4af2-955c-ebad5f55e3cb.png)

Here is a [collab notebook](https://colab.research.google.com/drive/1FD1251MIk3LWF-Ar5myeT84FTUuD-277?usp=sharing) that reproduces this result.

To verify that the data is preprocessed correctly and contains some signal, we computed noise ceiling metric directly on the normalized fMRI time series values. Here is the noise ceiling at 10s after stimulus onset:

![image](https://user-images.githubusercontent.com/5416313/173338592-947eb868-c82e-4172-969f-43af0c883ab5.png)

This looks closer to some of the GLMsingle results on NSD.

Any ideas on what may have gone wrong with the application of GLMsingle would be appreciated.

Thanks,
Cory

**Comment by kendrickkay** [comment]
Hi Cory, 

Thanks for all of the useful diagnostic information. I think I followed it.

I agree that visually, the direct method you showed (last image) does a better job of visually separating what is likely signal voxels from what is likely noise voxels.

With respect to the figures depicting some of the GLMsingle outputs, I am not entirely sure the figures indicate that something went wrong.  A direct comparison would be to try to compute a 'noise ceiling' on the GLMsingle outputs in exactly the same way as you did in the direct method and then compare directly (with same color map, slice, etc.)

Nonetheless, there could certainly be some details to consider in how you applied GLMsingle.  Here are a few things that come to mind:
1. Did you use a stimdur of 8 s? (Looking at the notebook, it appears you did.) That implies that you expect a sustained neural activity over the course of the 8-s trial. I wonder if that is reasonable.
2. Does the dataset include data from different scan sessions (scanner visits)?  There may be large gain differences across scanner visits.  When you mention "normalized fMRI time series values" did this involve something like "divide by std dev of each run (or scan session)?"  You will probably want to apply GLMsingle to data from individual scan sessions, and then concatenate the single trial responses across scan sessions possibly with some session-wise voxel-wise normalization to account for gain differences.
3. Visually comparing the figure outputs to NSD might be misleading, given that NSD was conducted at 7T where possibly the SNR is substantially higher...

**Comment by kendrickkay** [comment]
Oh, also, I forgot: the <sessionindicator> input might be helpful if you specifically want to use data collected from different days in a single call to GLMsingle

**Comment by kendrickkay** [comment]
Finally, I just added some information to https://glmsingle.readthedocs.io/ , which might be useful to you to read through.

**Comment by efirdc** [comment]
> A direct comparison would be to try to compute a 'noise ceiling' on the GLMsingle outputs in exactly the same way as you did in the direct method and then compare directly (with same color map, slice, etc.)

Good point. I will run GLMsingle on the entire training set and compute the betas there.

1. I will try a grid of stimulus durations to see what works best.
2. The reason for taking runs from different sessions is that there are no repeated images within each session. I have organized runs into groups of 5 where the same images were displayed, but these runs are always from different sessions. I assumed it was important for GLMsingle to have some repeated images for cross-validation purposes, but I might be wrong about that. Do you think I should switch to grouping runs by session, even though there are no repetitions? If not I will look into the `sessionindicator` parameter.,
3. Good point. I should compare to the results on BOLD5000 instead.

**Comment by kendrickkay** [comment]
Regarding gridding stimulus durations - that seems a bit overkill. I was just mentioning it for intellectual completeness.

Regarding repeated images, yes, you ideally give GLMsingle data reflecting some repeated images for cross-validation purposes.  Since your repeated images come across sessions, then, yeah a good approach would be to use data from multiple sessions and use the 'sessionindicator' parameter.  It sounds like you are specifically selecting specific runs from different sessions.  Unless there is a reason not to, why not just analyze all the data (e.g. all runs)?  Even if some conditions (images) have only single presentations, that isn't a problem.  (In fact, both NSD and BOLD5000 have many conditions (within a given call to GLMsingle) for which only one trial is available.)

**Comment by efirdc** [comment]
Hi,

Just coming back to this recently. I was able to run the onoff and fithrf stages on all 120 runs, but it crashes on the glmdenoise stage:

```
*** Saving results to /Deep-Image-Reconstruction/glmsingle/run2/TYPEB_FITHRF.hdf5. ***

*** DETERMINING GLMDENOISE REGRESSORS ***

*** CROSS-VALIDATING DIFFERENT NUMBERS OF REGRESSORS ***

chunks:   0%|                                                                                                                | 0/4 [3:43:01<?, ?it/s]
Traceback (most recent call last):
  File "/code/fmri-preprocessing/kamitani.py", line 150, in <module>
    Fire(run_all)
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/code/fmri-preprocessing/kamitani.py", line 138, in run_all
    results_glmsingle = glmsingle_obj.fit(
  File "/usr/local/lib/python3.9/site-packages/glmsingle/glmsingle.py", line 1098, in fit
    glmbadness[relix, :] = calcbadness(
  File "/usr/local/lib/python3.9/site-packages/glmsingle/ssq/calcbadness.py", line 98, in calcbadness
    testcols = np.asarray(validcolumns[testix])
TypeError: list indices must be integers or slices, not list
```
Any idea on the cause of this error? 

Here is the `glmsingle_obj` initialization:

```python
glmsingle_obj = GLM_single(dict(
    wantlibrary=1,
    wantglmdenoise=1,
    wantfracridge=1,
    wantfileoutputs=[1,1,1,1],
    wantmemoryoutputs=[1,1,1,1],
    sessionindicator=np.arange(1, 16).repeat(8)[None],
    xvalscheme=[list(fold) for fold in np.split(np.arange(1, 121), 5)],
    wanthdf5=1
))
```

Also I am wondering if there is a way to resume at the glmdenoise stage? It took 32 hours to fit the type A and B models so it would be ideal to resume at denoising. I'm assuming glmdenoise uses the hrf indices determined in the fithrf stage, but I'm not sure how that would work when resuming.

Thanks,
Cory

**Comment by kendrickkay** [comment]
Sorry for the delay.  It is likely a trivial Python data type bug.  We are trying to find time to diagnose this, sorry for the delay

**Comment by kendrickkay** [comment]
hi - see #75 which should fix the crash. 

As for "resuming", i will note this as a future possible enhancement.  For now, hopefully you can proceed.  Feel free to re-open this issue if you see any remaining issues or have more discussion.  

Sorry for the delay.
