### ISSUE TITLE
Trials with different durations

### ISSUE THREAD

**Issue by miladmozafari** [cvnlab/GLMsingle#83]
Hello,

Thank you for this great toolbox!
I would like to use GLMSingle on one of our large fMRI datasets; however, in some of the runs, we have a particular trial that is much longer (10s) than regular ones (3s). Based on the examples and documentation, I can only pass a single stimulus duration for all the runs. Any workarounds for this case?

**Comment by kendrickkay** [comment]
We put some thoughts on https://glmsingle.readthedocs.io/en/latest/wiki.html - see what you think.

The main question in your case would be: what do you believe about the duration of neural activity in the 10s case compared to the 3s case?

**Comment by miladmozafari** [comment]
Sorry for my super late response and thanks for the pointer. I should have read the wiki first!
I see your point and I agree this is challenging (even more challenging in our case). During the 10 seconds, our subjects have to perform an imagery task and they should try to reinforce their imagination as much as possible.

**Comment by kendrickkay** [comment]
Oh, I see.  One simple idea is just code the 10-second period, as, say, a series of 3 distinct 3-s trials, with the idea as if you would be estimating 3 different amplitude levels for a single 10-second trial.   (Who knows, in theory, the brain response may be fluctuating in interesting ways across the 10-s period.)   Then, when you go to analyze the single trial betas, you could certainly just average over those 3 amplitude levels if you want (or do whatever else you like).
