### ISSUE TITLE
Decomposing condition into subconditions via design matrix

### ISSUE THREAD

**Issue by andreifoldes** [cvnlab/GLMsingle#86]
Hello, 
Can glmsingle be tweaked so that its able to decompose an AB trial/condition into its constituent A and B beta amplitudes?

I tried using the following design matrix and I do get an output, but it's twice the size of the actual trials and I'm unsure whether I can trust it  and what its accompanying logic is - how would glmsingle chose which trial is choosing to estimate in the first case (R4 or R5)?

![image](https://user-images.githubusercontent.com/7458009/212777030-67e154de-76ae-45d4-9939-6341cdb95279.png)

**Comment by kendrickkay** [comment]
Hi Andrei - I'm not sure I quite follow.  Are you saying that for a given trial X, the trial might be one of two types?

It is up to you how to conceptualize your experiment.  For each trial, you must decide what kind of trial it is, and whether that kind of trial every is repeated elsewhere in your experiment.  And then code the trials accordingly.

If, alternatively, you are referring to multiple subcomponents in a trial, check out "What about trial subcomponents" at https://glmsingle.readthedocs.io/en/latest/wiki.html#what-about-trial-subcomponents

**Comment by andreifoldes** [comment]
Hi Kendrick,

> Are you saying that for a given trial X, the trial might be one of two types?
Let's say we are showing a participant two images next to each other, simultaneously e.g.: Trial1: Im1+Im2; Trial2: Im2+Im3; Trial3: Im3+Im4 .. and goal would be to get Im[1...N] level estimates (item-level/image-level).

`If, alternatively, you are referring to multiple subcomponents in a trial, check out "What about trial subcomponents" at https://glmsingle.readthedocs.io/en/latest/wiki.html#what-about-trial-subcomponents`
Right.. unfortunately this is not the case here because the subcomponents need to sequentially follow each other in the example, where in my case I'm dealing with simultaneous presentation.

I thought maybe I could somehow force glmsingle to estimate item-specific betas, to get it to estimate the "unique" activation from "image pair" trials  eg..: Estimating Im2 activation pattern from  Im1-Im2 >> Im2-Im3 type trial structure. Would you say the best thing one can do in this situation is use glmsingle to estimate unique (pair-specific) trial-level betas and then just do linear decomposition on those values to get approximate item-specific values

**Comment by kendrickkay** [comment]
Oh I see.  Thanks for the explanation.

Yes, what you are looking for (isolating Im1 from Im1+Im2, for example) is very tricky, as it relies on all sorts of assumptions.

What you suggested is reasonable -- the idea being just get GLMsingle to do some trial level estimates, and then it's up to posthoc analyses performed by yourself to deal with "estimating item specific" stuff.

One more idea:   You could, under the cost of making heavy assumptions, impose some interpretation on the application of GLMsingle.  For example, if you can reasonably assume that for a left-hemisphere visual voxel that it only cares about the images in the right hemisphere, then, you can prepare a special coding of the experiment geared and concerned only with the content of the experiment in the right hemisphere.
