### ISSUE TITLE
Activations outside the brain

### ISSUE THREAD

**Issue by jungtak05** [cvnlab/GLMsingle#94]
Hi,

Thank you for providing the great toolbox.

When I applied this toolbox to my data using MATLAB, I encountered strong activations outside the brain, as shown in Figure 1.
Specifically, I estimated 4D beta data and converted it to a Nifti file within non-noise voxels (i.e., pcvoxels). During this conversion process, I used the niftiwrite() function to create a 4D brain map. I included the information from the header of the input functional data for each participant, which was previously normalized to the MNI space.

I'm seeking advice on how to handle these activations outside the brain.

Any assistance would be greatly appreciated.

Kind regards,
Jungtak Park

Figure 1. Estimated beta map with MNI image.
![image](https://github.com/cvnlab/GLMsingle/assets/67935585/b116e0c7-b595-4432-b1e8-5e229f4946d2)

**Comment by kendrickkay** [comment]
Hi, a few comments:
- I am not entirely sure what you are plotting, but the existence of beta weights outside of the brain is not necessarily a problem. There are signal intensities outside of the brain, and in terms of estimating the model, the model in theory should still give "valid" percent signal change (PSC) estimates.  Now, certainly, the PSC estimates may have extreme instable values (like more than 50% PSC) and these values are likely completely unreliable and meaningless.  From a user's standpoint, you can simply ignore out-of-brain voxels.
- You mentioned perhaps using the 'pcvoxels' to mask your data. This does not seem like a good idea. The pcvoxels determination is used internally to the GLMsingle procedure, and from the user's perspective, you may not need to worry about that.  Simplest would be to just use the full 4D dataset as-is.

**Comment by iancharest** [comment]
We will close this issue now, feel free to reopen if you had any remaining issues with out of brain activations.
