### ISSUE TITLE
Different stimdur for different conditions

### ISSUE THREAD

**Issue by yqliu9240** [cvnlab/GLMsingle#95]
Hello!

  I am trying to apply GLMsingle to my data where some conditions have a stimdur of 2secs and some 6secs. But the GLMestimatesingletrial.m script seems to only take one single stimdur. Is there a way to get around this? 

Thank you!
Yuqi

**Comment by kendrickkay** [comment]
This is covered on the FAQ (https://readthedocs.org/projects/glmsingle).  I've updated a bit (but may take a while to show up.)   See screenshot below:
<img width="957" alt="image" src="https://github.com/cvnlab/GLMsingle/assets/2728338/c667b566-1da5-4fd5-a7e6-3751424ad1b6">

**Comment by yqliu9240** [comment]
That makes sense, thank you for the help!
