### ISSUE TITLE
How to build design matrix?

### ISSUE THREAD

**Issue by Cupid777** [cvnlab/GLMsingle#96]
hi,
    I use the fMRI data with TR=2s, stimulus duration=5s (3s picture stimuli and 2s blank), and I don't know how to build this design matrix, could you give me some suggestions? 

Thank you!

**Comment by kendrickkay** [comment]
I think the easiest would be to resample your fMRI data to 1 s.  Then, code the onset of the picture stimuli and use a <stimdur> of 3 s.

**Comment by Cupid777** [comment]
Thanks a lot!
I also have a question, set the parameter “stimdur” in singleGLM 3 or 5 under this fMRI data?

**Comment by kendrickkay** [comment]
You should set it to 3.  The idea is that GLMsingle will internally convolve an impulse response with a square wave of duration 3 s, to try to approximate what the evoked HRF might be.  In the end, it's only a guess, so it's not a big deal if it's slightly inaccurate. Indeed, the whole point of the HRF library is to accommodate for some variation.   The 2-s blank is not expected to be part of the evoked response, so it's irrelevant.

**Comment by Cupid777** [comment]
Thanks a lot! 
But I find the parameter “stimdur” was set as 4 (though 3s stimuli and 1s blank) in the example2.ipynb. You mean that setting either 3 or 4 is okay?

**Comment by Cupid777** [comment]
> I think the easiest would be to resample your fMRI data to 1 s. Then, code the onset of the picture stimuli and use a of 3 s.

The TR of raw fMRI data is 2s, it may not be resampled to 1s?

**Comment by kendrickkay** [comment]
The user is expected to set stimdur to whatever fits their experiment.

You may need to intentionally resample your current fMRI to 1 s.

I would suggest going through the examples and the FAQ.

**Comment by Cupid777** [comment]
Thank you very much！
